NEW (Extension) @W-16833947@ Add rule to require a minimum API version of abstract/virtual classes with private methods
forcedotcom/code-analyzer-translator pull request #101
Opened 2024-10-06 21:47 UTC by jag-j

2024-10-07 14:20 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +            fileContents = fileContents + await fs.promises.readFile(fileName + "-meta.xml", {encoding: 'utf8'}) ;
A few things here.
First, this seems to assume that the <fileName>-meta.xml file exists and are attempting to read it without first checking.
Second, if you do check if it exists, you must stay within the workspace provided... so you'll need to see if the file exists among the files provided by the workspace only (and not checking on disk).

2024-10-07 14:20 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Detects private methods within abstract/virtual classes`,
This should say something about the version.

2024-10-07 14:20 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Found private methods within abstract/virtual classes. Make sure the corresponding API version of the class is at least v61.0. If so, you can ignore this rule.`,
Shouldn't this be updated as well... why would someone need to ignore it if your version check ideally handles the correct range?

2024-10-07 14:20 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +    include_metadata?: boolean;
Please add a comment saying this "INTERNAL USE ONLY (NOT EXPOSED TO USER CONFIG)"

2024-10-08 11:32 UTC, jag-j commented on packages/code-analyzer-regex-engine/src/engine.ts
> +            fileContents = fileContents + await fs.promises.readFile(fileName + "-meta.xml", {encoding: 'utf8'}) ;
Sure, I should check for the existence of -meta.xml file. But that ideally should never be the case in a real world project and in case the meta file isn't found, I want to silently proceed instead of throwing an error.

To your second point, let's assume someone says "--workspace ./force-app/**/*.cls" to scan their apex files, we should still be checking for the corresponding -meta.xml files from the disk rather than just limiting to the workspace. The user doesn't case this rule takes into account -meta.xml files and we shouldn't be expecting them to explicitly define that in their command.

2024-10-08 12:56 UTC, stephen-carter-at-sf requested changes

2024-10-08 12:56 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +                fileContents = fileContents + await fs.promises.readFile(medataFileName, {encoding: 'utf8'}) ;
The contract of the engine is to not escape the boundaries of the workspace. So you should be checking to see if the file exists in the Workspace.getExpandedFiles() array instead of looking on disk (which the getExpandedFiles does automatically already).

2024-10-08 13:05 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +    include_metadata?: boolean;
The default isn't false... its undefined. I don't think we need to specify what the default is... so maybe just remove the commont on line 51.

2024-10-08 13:05 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(?=.*(?<=<apiVersion>)([1-9]|[1-5][0-9]|60)(\.[0-9])?(?=<\/apiVersion>))public\s+(virtual|abstract)\s+class\s+\w+\s*\n*\s*{\s*(?:[^{}]*{[^{}]*})*?\s+private\s+\w+\s+\w+\s*\([^)]*
If someone writes `<apiVersion>53.0</apiVersion>` then this looks good... but if they do:
```
<apiVersion> 53.0 </apiVersion>
```
or if they do
```
<apiVersion>
  53.0
</apiVersion>
```
Then this would miss it. So shouldn't we add in `\s*` before and after the numbers?

2024-10-08 13:05 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(?=.*(?<=<apiVersion>)([1-9]|[1-5][0-9]|60)(\.[0-9])?(?=<\/apiVersion>))public\s+(virtual|abstract)\s+class\s+\w+\s*\n*\s*{\s*(?:[^{}]*{[^{}]*})*?\s+private\s+\w+\s+\w+\s*\([^)]*
Also... why `\s*\n*\s*`... that seems redundant... Did you mean `\s*\n+\s*`? If not, then why not just do `\s*`

2024-10-08 13:05 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(?=.*(?<=<apiVersion>)([1-9]|[1-5][0-9]|60)(\.[0-9])?(?=<\/apiVersion>))public\s+(virtual|abstract)\s+class\s+\w+\s*\n*\s*{\s*(?:[^{}]*{[^{}]*})*?\s+private\s+\w+\s+\w+\s*\([^)]*
Why is `\s*(?:[^{}]*{[^{}]*})*?` needed?

2024-10-08 13:13 UTC, stephen-carter-at-sf requested changes

2024-10-08 13:13 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/test/engine.test.ts
> +                        startColumn: 1,
This seems wrong. It appears that the violation doesn't point to the private method... but points to the start of the class up until the end of the private method. I would have expected the startLine to be the start of the private method.

2024-10-08 13:13 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/test/engine.test.ts
> +                        startLine: 1,
ditto.

2024-10-08 13:16 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/test/test-data/apexClassWithPrivateMethod/testClassWithoutCorrespondingMetadataFile.cls
> +}
Can you please have at least one example where the public method comes before the private method?

2024-10-08 13:20 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(?=.*(?<=<apiVersion>)([1-9]|[1-5][0-9]|60)(\.[0-9])?(?=<\/apiVersion>))public\s+(virtual|abstract)\s+class\s+\w+\s*\n*\s*{\s*(?:[^{}]*{[^{}]*})*?\s+private\s+\w+\s+\w+\s*\([^)]*
Lastly... I believe you need to do look aheads and behinds on everything except for the private method so that you get the correct start and end locations.

2024-10-08 13:25 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(?=.*(?<=<apiVersion>)([1-9]|[1-5][0-9]|60)(\.[0-9])?(?=<\/apiVersion>))public\s+(virtual|abstract)\s+class\s+\w+\s*\n*\s*{\s*(?:[^{}]*{[^{}]*})*?\s+private\s+\w+\s+\w+\s*\([^)]*
Try this as a use case please:

```
public abstract class Parent {
    public void aMethod() {
     if(true) {
       aPrivateMethod();
     }
    }


    private void aPrivateMethod() { // This should be the start line
     if(true) {
       System.debug('Parent private method is called.');
     }
    } // This should be the end line
}
```

2024-10-08 13:27 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +                fileContents = fileContents + await fs.promises.readFile(medataFileName, {encoding: 'utf8'}) ;
Just saw your previous comment. Yeah I think we'll have to ask John if he wants us to break the contract of going outside the provided workspace.

2024-10-08 15:24 UTC, jag-j commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(?=.*(?<=<apiVersion>)([1-9]|[1-5][0-9]|60)(\.[0-9])?(?=<\/apiVersion>))public\s+(virtual|abstract)\s+class\s+\w+\s*\n*\s*{\s*(?:[^{}]*{[^{}]*})*?\s+private\s+\w+\s+\w+\s*\([^)]*
I agree with all the suggestions, except for the space before and after version number. Since this is an autogenerated file, I am not sure if it is worth catching the other variants. I will leave it as is. I will include the above class in one of the tests.

2024-10-09 13:26 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(?=.*(?<=<apiVersion>)([1-9]|[1-5][0-9]|60)(\.[0-9])?(?=<\/apiVersion>))public\s+(virtual|abstract)\s+class\s+\w+\s*\n*\s*{\s*(?:[^{}]*{[^{}]*})*?\s+private\s+\w+\s+\w+\s*\([^)]*
I believe the regular expression you want is:

```
// Part to match (using look behind) that we are in an abstract/virtual class (using look behind):
//    (^|\s+)(virtual|abstract)[^{]*\s+class\s+.*
// Part to match a private method signature:
//    private [^{]+\([^)]*\)\s*{
// Part to match (using look ahead) that the meta data has apiVersion less than 61.0:
//    .*<apiVersion>\s*([1-9]|[1-5][0-9]|60)(\.[0-9])?\s*<\/apiVersion>
const re = /(?<=(^|\s+)(virtual|abstract)[^{]*\s+class\s+.*)private [^{]+\([^)]*\)\s*{(?=.*<apiVersion>\s*([1-9]|[1-5][0-9]|60)(\.[0-9])?\s*<\/apiVersion>)/gis
```

2024-10-09 18:50 UTC, stephen-carter-at-sf approved these changes

2024-10-09 18:59 UTC, merged