CHANGE @W-16867469@ Added comment property to code location in outfile
forcedotcom/code-analyzer-translator pull request #110
Opened 2024-10-29 15:17 UTC by jfeingold35

2024-10-29 15:22 UTC, jfeingold35 commented on packages/code-analyzer-core/test/rule-selection.test.ts
> +            6.666666666666667, // average of 20 from engine1, 0 from engine2, 0 from engine3
@stephen-carter-at-sf , why can we assume a consistent ordering of the emit messages? I'm willing to believe that we can, but I'd just like to understand why.

2024-10-29 19:49 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/test/rule-selection.test.ts
> +            6.666666666666667, // average of 20 from engine1, 0 from engine2, 0 from engine3
We could if you want... another option is to change the test to just check the first (0) and last values (100) ... and then check that all other values increase each time... so update line 332 to just check that the type is equal to EventType.RuleSelectionProgressEvent as its own assertion, the timestamp is equal to sampleTimestamp with its own assertion, and then just check the precentComplete[i] > percentComplete[i-1].

2024-10-29 20:29 UTC, stephen-carter-at-sf requested changes

2024-10-29 20:29 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +                'endLine', 'endColumn', 'locations', 'message', 'resources'],
I was expecting to also see primaryLocationIndex here... but I'm not sure if we need it for CSV format or not. What are your thoughts? Does the index make sense if it is a stringified list anyway?

2024-10-29 20:29 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +    }
I see you removed the createLocationString function which has conditionals around the file, startline, startColumn, etc.

Because the interface has | undefined:
```export interface CodeLocation {
    getFile(): string | undefined
    getStartLine(): number | undefined
    getStartColumn(): number | undefined
    getEndLine(): number | undefined
    getEndColumn(): number | undefined
}
```

Then even though we control the only engine that is creating path locations... the interface allows a 3rd party engine to create code locations that don't have the file, line, column, endLine, endColumn possibly filled in.

At the top level this comes up with the UnexpectedEngineErrorViolation... but currently it doesn't come up within the getCodeLocationsOutput for the Flow and DataFlow types.

But I still think we should program to the interface and not to our internal expectations - because a 3rd party engine could very well set the  RuleType to Flow or DataFlow and then not contractually have to set these values - or they could just use something equivalent to our UndefinedCodeLocation.

So I recommend fixing this. You'll have to also update the getFile, getLIne, getColumn to also have `| undefined`.

Alternatively if you want to stick with this assumption... where you are putting in `!` marks on lines 75,76,77 ... maybe instead you should make these formal assertions with a human readable error message that says something like:
```
Unexpected error: Violation of type '%s' from engine '%s' produce a code location with an undefined file, line, or column field.
```
but this would require you putting the check outside of the constructor where you still have access to the violation information.

2024-10-29 20:29 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/test/stubs.ts
> +            this.createdEngines.set(engineName, new StubEngine3(config));
In the future... feel free to create another stub plugin with its own stub engine local to the test file you want to update. This way you won't need to update all the tests everywhere that use this shared set of stubs. But this is all fine of course.

2024-10-29 20:29 UTC, stephen-carter-at-sf commented on packages/code-analyzer-engine-api/src/results.ts
> +    comment?: string
As a fast follow on... we'll need to create a PR to update the version number of the engine-api and core... which will have a trickle effect on all other packages that depend on the engine-api.

We at some point should discuss a release strategy soon with regards to keeping these version numbers correct... i'm thinking we can update them to say something like
0.12.0-SNAPSHOT
for example when we make a change. Then prior to deployment we would update it to 0.12.0. To be discussed later... but let's not forget that the engine api has changed and thus we need to increment its version this month and release.

2024-10-29 20:29 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/important.txt
> +python3 /Users/jfeingold/Code/code-analyzer-core/packages/code-analyzer-flowtest-engine/pipx.pyz run --no-cache --spec . -- flowtest -h
What is this? Did you accidentally have this in your changelist. If so - please remove so that it doesn't get checked in.

2024-10-29 20:30 UTC, jfeingold35 commented on packages/code-analyzer-core/src/output-format.ts
> +                'endLine', 'endColumn', 'locations', 'message', 'resources'],
My view was that the index didn't make sense for a stringified list.

2024-10-29 20:32 UTC, jfeingold35 commented on packages/code-analyzer-core/src/output-format.ts
> +    }
Sure, I can change this so it no longer assumes that `startLine`, `startColumn`, and `file` are defined.

2024-10-29 20:34 UTC, jfeingold35 commented on packages/code-analyzer-core/test/stubs.ts
> +            this.createdEngines.set(engineName, new StubEngine3(config));
I actually considered doing that when I saw how many files I'd have to change, but then I decided it was actually probably worth making the changes, just so that the other tests use engines with rules that are Flow-typed in addition to the existing Standard and DataFlow ones.

2024-10-29 20:35 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/important.txt
> +python3 /Users/jfeingold/Code/code-analyzer-core/packages/code-analyzer-flowtest-engine/pipx.pyz run --no-cache --spec . -- flowtest -h
Good catch, that was my bad.

2024-10-30 12:37 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +        return `${this.file}:${this.line}:${this.column}${commentPortion}`;
I still see that there is no conditionals on the file. If you look at how createLocationString was implemented... we wouldn't return an empty string if there was no file. And we wouldn't return the column info if there was no line info, etc.

Did you want to change this to what you have? If so.. what does it look like... would it say "undefined:3:undefined" if it has a line for example?

2024-10-30 15:12 UTC, stephen-carter-at-sf approved these changes

2024-10-30 15:20 UTC, merged