NEW @W-17100356@ Add sarif formatter to output formats
forcedotcom/code-analyzer-translator pull request #117
Opened 2024-11-07 18:38 UTC by jag-j

2024-11-07 19:23 UTC, jfeingold35 commented on packages/code-analyzer-core/test/test-data/expectedOutputFiles/multipleViolations.goldfile.sarif
> +          "level": "warning"
What's the deal with this `level` property? Are the only values `warning` and `error`?

2024-11-07 19:27 UTC, jag-j commented on packages/code-analyzer-core/test/test-data/expectedOutputFiles/multipleViolations.goldfile.sarif
> +          "level": "warning"
yes, there is only warning and error. So decided to go with 2 and below as error and others as warning.

2024-11-07 19:33 UTC, stephen-carter-at-sf requested changes

2024-11-07 19:33 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/package.json
> +    "@types/sarif": "^2.1.4",
Any reason why you chose 2.1.4 instead of 2.1.7?

2024-11-07 19:33 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +import { Log, Run, Result, ReportingDescriptor, Location, Region, Notification } from "sarif";
These names are very common. So either let's move the SarifOutputFormatter into its own file... or ... just import this as import * as sarif from "sarif" so that you can then refer to these common names as sarif.Log, sarif.Run, etc.

2024-11-07 19:35 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +		return rules;
Please remove tab characters from your files... only spaces please for this repo.

2024-11-07 19:42 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/test/test-data/expectedOutputFiles/multipleViolations.goldfile.sarif
> +          "ruleId": "stub3RuleA",
This rule is of type "Flow" and it has multiple locations which make up the path.

Soon we'll also have type "MultiLocation" for CPD results which have multiple locations. 

So shouldn't we be populating the result with multiple locations in these cases?

2024-11-07 19:43 UTC, jag-j commented on packages/code-analyzer-core/package.json
> +    "@types/sarif": "^2.1.4",
Since 4.x uses 2.1.4, I used the same so this doesn't bring in any variation during comparison.

2024-11-07 19:43 UTC, jag-j commented on packages/code-analyzer-core/src/output-format.ts
> +import { Log, Run, Result, ReportingDescriptor, Location, Region, Notification } from "sarif";
Good point. I will do this.

2024-11-08 15:23 UTC, stephen-carter-at-sf requested changes

2024-11-08 15:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +                });
This isn't what I was expecting.

I thought we agreed that:
* Only if the data type is MultiLocation, Flow, and DataFlow (which can be determined with a new subfunction - to also help update the other locations which have things like
```
        primaryLocationIndex: [RuleType.DataFlow, RuleType.Flow].includes(rule.getType()) ? violation.getPrimaryLocationIndex() : undefined,
        locations: [RuleType.DataFlow, RuleType.Flow].includes(rule.getType()) ? createCodeLocationOutputs(codeLocations, runDir) : undefined,
```
) would we populate the relatedLocations
* And 2nd... we would all of the locations - including the primary... using the relatedLocations as the full path or full set of locations. 

That is, I thought the goal was to use the locations field to just hold the primary location... and then for types MultiLocation, Flow, and DataFlow to have the relatedLocations hold the all the locations (which represent the path, etc). This is essentially how the json, xml, etc format works - so I was hoping to be consistent.

2024-11-08 21:17 UTC, stephen-carter-at-sf requested changes

2024-11-08 21:17 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +                if(violation.primaryLocationIndex && violation.locations) {
You should be using `typeSupportsMultipleLocations(violation.getRule().getType())` here.

2024-11-08 21:17 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +        }
Oh now I see why you are having difficulties. It looks like you are using the ViolationOutput data structure which was the data structure used to help generate json and xml.

You should be just iterating over the results.geEngineNames() and then using runResults.getEngineRunResults(engineName).

2024-11-08 21:25 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +}
Maybe just pass in the RuleType instead of the rule.

2024-11-11 16:30 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +        }
This isn't needed. The results are already available per engine via `results.getEngineRunResults(engineName)`

So just loop over the engine names and then in the loop get the results for that engine.

2024-11-11 16:30 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +                if(typeSupportsMultipleLocations(violation.getRule().getType())) {
The cyclometic complexity is quite high. 

One trick to address this, is to separate each transformation into its smallest unit.

The resulting code could look like:

```
class SarifOutputFormatter implements OutputFormatter {
    format(results: RunResults): string {
        const runDir = results.getRunDirectory();

        const sarifRuns: sarif.Run[] = results.getEngineNames()
            .map(engineName => results.getEngineRunResults(engineName))
            .filter(engineRunResults => engineRunResults.getViolationCount() > 0)
            .map(engineRunResults => toSarifRun(engineRunResults, runDir));

        // Construct SARIF log
        const sarifLog: sarif.Log = {
            version: "2.1.0",
            $schema: 'http://json.schemastore.org/sarif-2.1.0',
            runs: sarifRuns,
        };

        // Return formatted SARIF JSON string
        return JSON.stringify(sarifLog, null, 2);
    }
}

function toSarifRun(engineRunResults: EngineRunResults, runDir: string): sarif.Run {
    const violations: Violation[] = engineRunResults.getViolations();
    const rules: Rule[] = [... new Set(violations.map(v => v.getRule()))];
    const ruleNames: string[] = rules.map(r => r.getName());

    return {
        tool: {
            driver: {
                name: engineRunResults.getEngineName(),
                informationUri: "https://developer.salesforce.com/docs/platform/salesforce-code-analyzer/guide/version-5.html",
                rules: rules.map(toSarifReportingDescriptor),
            }
        },
        results: violations.map(v => toSarifResult(v, ruleNames.indexOf(v.getRule().getName()))),
        invocations: [
            {
                executionSuccessful: true,
                workingDirectory: {
                    uri: runDir,
                },
            },
        ],
    };
}

function toSarifResult(violation: Violation, ruleIndex: number) : sarif.Result {
    const primaryCodeLocation = violation.getCodeLocations()[violation.getPrimaryLocationIndex()];
    const result: sarif.Result = {
        ruleId: violation.getRule().getName(),
        ruleIndex: ruleIndex,
        message: { text: violation.getMessage() },
        locations: [toSarifLocation(primaryCodeLocation)],
        level: toSarifNotificationLevel(violation.getRule().getSeverityLevel()),
    };
    if(typeSupportsMultipleLocations(violation.getRule().getType())) {
        result.relatedLocations = violation.getCodeLocations().map(toSarifLocation);
    }
    return result;
}

function toSarifLocation(codeLocation: CodeLocation): sarif.Location {
    return {
        physicalLocation: {
            artifactLocation: {
                uri: codeLocation.getFile(),
            },
            region: {
                startLine: codeLocation.getStartLine(),
                startColumn: codeLocation.getStartColumn(),
                endLine: codeLocation.getEndLine(),
                endColumn: codeLocation.getEndColumn()
            } as sarif.Region
        }
    }
}

function toSarifReportingDescriptor(rule: Rule): sarif.ReportingDescriptor {
    return sarif.ReportingDescriptor = {
        id: rule.getName(),
        properties: {
            category: rule.getTags(),
            severity: rule.getSeverityLevel()
        },
        helpUri: rule.getResourceUrls().length > 0 ? rule.getResourceUrls()[0] : '';
    }
}

function toSarifNotificationLevel(severity: SeverityLevel): sarif.Notification.level {
    return severity < 3 ? 'error' : 'warning';
}
```

2024-11-11 17:18 UTC, stephen-carter-at-sf approved these changes

2024-11-11 17:40 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/src/output-format.ts
> +    }
Again this isn't needed. The violations are already grouped by engine.

2024-11-11 18:32 UTC, stephen-carter-at-sf approved these changes

2024-11-11 18:44 UTC, merged