CHANGE @W-17042378@ Updated HTML template with comment property.
forcedotcom/code-analyzer-translator pull request #119
Opened 2024-11-08 22:34 UTC by jfeingold35

2024-11-09 00:54 UTC, jag-j commented on packages/code-analyzer-core/output-templates/html-template-0.0.1.txt
> +        constructor(data2) {
What are these changes about renaming data to data2 ?

2024-11-11 16:46 UTC, stephen-carter-at-sf requested changes

2024-11-11 16:46 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/output-templates/html-template-0.0.1.txt
> +        constructor(data2) {
It looks like Marcelino made that rename. Josh basically just copied what he got from https://git.soma.salesforce.com/cli-scanner/code-analyzer-report/blob/main/dist/index.html

2024-11-11 16:46 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/output-templates/html-template-0.0.1.txt
> +          <strong>Code Analyzer Report</strong> – Jun 26th, 2024 3:24pm
Josh - we need to add back in the dynamic timestamp here.

2024-11-11 16:48 UTC, stephen-carter-at-sf requested changes

2024-11-11 16:48 UTC, stephen-carter-at-sf commented on packages/code-analyzer-core/test/test-data/expectedOutputFiles/multipleViolations.goldfile.html
> +      const data = [{"rule":"stub1RuleA","engine":"stubEngine1","severity":4,"type":"Standard","tags":["Recommended","CodeStyle"],"file":"test/config.test.ts","line":3,"column":6,"endLine":11,"endCol
Your files like `test/config.test.ts` should be `test{{PATHSEP}}config.test.ts` to make this gold file platform independent

2024-11-12 16:18 UTC, stephen-carter-at-sf approved these changes

2024-11-12 16:42 UTC, merged