NEW (RegexEngine): @W-16150675@ Implemented API versioning private method rule
forcedotcom/code-analyzer-translator pull request #42
Opened 2024-07-10 16:49 UTC by ravipanguluri

In this PR:

  * Implement tests that impose intended behavior of the API versioning to catch all instances of private virtual classes when the API version is below a threshold
  
  * When RegexEngine's describeRules() method is called, two rules are returned "PrivateMethodAPIVersionRule", "TrailingWhitespaceRule"
  
  * Implement logic for a rule that warns users when both of the following occur: the user declares a virtual class has private members and their API version 60.0 and below.
  
  *Code refactoring done for more sensible splitting of code logic and execution

2024-07-10 20:14 UTC, stephen-carter-at-sf requested changes

2024-07-10 20:14 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +/*Could make this convenience function globally available, but for now just copy-pasting from eslint engine */
Please remove this comment. 

The getMessageFromCatalog is globally available. But your convenience getMessage function uses your MESSAGE_CATALOG so you don't need to export it and use it everywhere... so we wouldn't make that globally available.

2024-07-10 20:14 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/RegexEnginePlugin.ts
> +        const violations: Violation[] = await this.regexExecutor.execute(filesToUse)
Your constructor and this method seems wrong. Since your TrailingWhiteSpaceRule is associated with your SimpleRegeExecutor and your PrivateMethodApiVersionRule is assocaited with your PrivateMethodApiVersionExecutor then shouldn't you be constructing one or more executors here based on what rules are selected and then running each of them, resolving their violations into a single output?

Again this is the down side of having these very different rules in the same engine.

2024-07-10 20:17 UTC, stephen-carter-at-sf requested changes

2024-07-10 20:17 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/test/engine.test.ts
> +            engine = new RegexEngine(new PrivateMethodApiVersionExecutor())
This is where I believe you went wrong. If you liked this constructor approach, then you would need to pass in all of your executors, and each executor would then need to tell your engine what rules it supports.

But before going too complicated, just start with a test that allows you to run all available rules at the same time.

2024-07-11 12:54 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/RegexEnginePlugin.ts
> +        }
A few things...
1) Shouldn't the executor determine which files to target? Any use of instanceof other than validating unknown types is usually a code smell.
2) You still are not using the ruleNames. So if the user only selected one of the rules, this would still run both of them.

2024-07-11 12:54 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/RegexEnginePlugin.ts
> +        this.regexExecutors = executors ? executors : [new SimpleRegexExecutor(), new PrivateMethodApiVersionExecutor()];
What is the purposes of passing in executors to the constructor?

And if not all executors are provided, then shouldn't the list of rules be dependendent on which executors are available?

2024-07-16 13:47 UTC, stephen-carter-at-sf requested changes
Just reviewed your source code so far. I'll review your test code soon.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/RegexEnginePlugin.ts
>          };
You aren't allowing rule selection to work. I didn't get a chance to review this code before... but the same pattern is happening with your metadata engine. The point of us passing in the rule names into the run method is because that is the list of rules that the user has selected.

Fortunately, you only have 1 rule right now on each of your engines, so this runRules method will currently only be called by the core module with the 1 rule (and core would never call with an empty ruleNames array). But ideally you would want the code setup today to prepare for multiple rules.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +export class MetadataExecutor {
I'm still struggling to understand what the point of the executor is (especially in the current Regex Engine). What I don't like about is that it is separating the rule description from the logic so that they aren't tied in any way together. In the future as we add in more rules... how would rule selection work?

If you were to have something like an Executor... then I would say what is its single responsibility? Currently it looks like... it executes a single rule and returns violations for that rule... but how does it know what to execute... and how is this different than the responsibility of the run method of the engine?

If instead, you wanted to tie this directly to the specific private method api version rule... then I would think that this would be named as such and would also contain the description information of the rule as well. Then the engine could essentially hold these rules and delegating to them to get their descriptions and to execute when needed.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +    }
Is there a reas you are storing the lineSep as state on the executor classes? os.EOL is simple enough to just pass in where we need it. Why store it?

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +                if (fileStats.isFile()) {
What is this isFile check for? It looks like you are already (inside of your engine) getting these allFiles from the getExpandedFiles which already returns nothing but files. So there are no folders in the mix anymore since you chose to work directly on files. 

So your entire execute method might end up simply being a single line:
```
    return Promise.all(allFiles.map(f => this.scanFile(f))).flat();
```

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +        const regex = /(?<=ApexClass.+>[\s\S]+<apiVersion>)[0-9\\.]+(?=<\/apiVersion>)(?=[\s\S]+<\/ApexClass>)/g
Parsing xml files with regex isn't ideal actually... especially if people add in comments into their xml file that you aren't considering.

So instead, see if you can find a way of using XPath with node.js. XPath is very commonly used in frontend javascript to navigate the html dom... but I believe node most likely offers the ability to start with an xml document and run an XPath query on it. Look into it.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +        const classDeclaration = `${accessModifier}\\s+${classType}\\s+class[^{]+(?={)`
With apex, is it possible to have public and virual and class on separate lines? Might want to experiment with apex to find out. If not, then we should reduce the expression to only be spaces and possible tab characters (if they are allowed).

Basically if a user had a comment where they ended with "public abstract" and then the next line was just a regular class... then we wouldn't want to pick these up.

Lastly, is it possible to flip the order of public virtual vs virtual public? Something to look into.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +        const classContentRegex = `([\\s\\S+]+)}`
Help me understand this.
Are you trying to find the entire class? If so, wouldn't this stop after the first if statement (or whatever else has a bracket). I don't know if we can with a regular expression find the end of the class definition. We might need to just stop at the signature without a formal AST.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +        }
It's best to put this in a helper method that's called fileExists or something. This is a common pattern in node to try to access it as a means of detecting if it exists since its the fastest way to know without doing a lookup.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +    }
The McCabe Cyclomatic Complexity of this file is probably very large due to all the nested conditionals.

I can show you some refactoring tricks on how to reduce this complexity which helps with readability, and helps avoid bugs.

One small trick that you should be doing is simply doing quick returns or filter operations.

I would have earlier one just wrote a boolean method that I could then use on my initial set of files to filter it down. Then only loop over the remaining files. Alternatively, just shift the code left by negating your conditional and do a quick return.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +            if (!this.isContentInComment(fileContents.slice(privateMethod.index, fileContents.length))) {
I'm a little confused by this. In order to tell if the privateMethod is inside of a comment... shouldn't you be checking the start of the file up to the index where you found the virtual private method in order to see if we are in a comment?
Instead it looks like you are get the oposite.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +    }
This handles the /* ... */ case it seems but what about the case where a user has

```
// private virtual class myClass...
```
as an inline comment?

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/messages.ts
> +        "Enforces a minimum API version for declaring private methods in abstract/virtual apex classes.",
I know this will get reviewed at some point... but to save the doc writer from doing more work, the term "Apex" will need a capital letter A believe. You might want to look through our help doc to see if Abstract and or Virtual also need to be capital letters

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/plugin.ts
> +    SeverityLevel, Violation,
nitpick:
If listing imports on multiple lines, then keep them all on their own line. Also, avoid trailing comma at the end of the list.

2024-07-16 13:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/test/engine.test.ts
> +    SeverityLevel, Violation
Ditto

2024-07-16 15:53 UTC, ravipanguluri commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +            if (!this.isContentInComment(fileContents.slice(privateMethod.index, fileContents.length))) {
Assuming that I am not given malformed apex when I am doing the search I am checking for an extra close without a matching open (if the method content is in a comment) because it indicates the open comment came before the method declaration . I could just have easily done it the way you're suggesting, I would just be looking for an extra open comment (without a required close before the method declaration) instead of an extra close comment. I think it works the same either way you do it.

2024-07-16 16:12 UTC, ravipanguluri commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +        const classDeclaration = `${accessModifier}\\s+${classType}\\s+class[^{]+(?={)`
Quickly checked both, and I think the answer to each is no. In which case, you're right in that I should just change the \s+ to [ \t]+.

2024-07-16 16:18 UTC, ravipanguluri commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +        const regex = /(?<=ApexClass.+>[\s\S]+<apiVersion>)[0-9\\.]+(?=<\/apiVersion>)(?=[\s\S]+<\/ApexClass>)/g
From some research, it appears that I can do it in node. But it would require extra libraries to do it, as node doesn't appear to support it natively.

2024-07-16 16:34 UTC, ravipanguluri commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +export class MetadataExecutor {
As for the regex to catch the private method declaration, I am worried about being able to effectively shove it all into a single regex expression (which would probably be needed to make it customizable because of the multiline comment case. This rule feels like somewhat of a special case even in the metadata world, so I am not entirely sure how to effectively incorporate it.

2024-07-16 16:44 UTC, ravipanguluri commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +        const classContentRegex = `([\\s\\S+]+)}`
The regex only ends the match after the last close bracket because the [\s\S]+ acts as a catch-all to make it match only the last }. Anyways there are tests where there are multiple private methods and the position of the private method is changed, so I think this expression works.

2024-07-16 18:42 UTC, stephen-carter-at-sf commented on packages/code-analyzer-metadata-engine/src/executor.ts
> +        const regex = /(?<=ApexClass.+>[\s\S]+<apiVersion>)[0-9\\.]+(?=<\/apiVersion>)(?=[\s\S]+<\/ApexClass>)/g
Yes if we have an xpath utility... it can be reused by us to more easily be able to create xpath based rules (and migrate the appexchange rules over here eventually). We can discuss in tomorrow's standup.

2024-07-17 16:15 UTC, stephen-carter-at-sf commented
Closing to start a new one.

2024-07-17 16:15 UTC, closed without merging