CHANGE @W-16438030] Make file extensions an optional field for regex engine rules
forcedotcom/code-analyzer-translator pull request #65
Opened 2024-08-07 19:30 UTC by ravipanguluri

In this PR:

A/C

 * Users can create custom regex rules without file extensions given
 * Any regex rule with no extensions given will run on all files in a workspace if they have text.

2024-08-07 21:21 UTC, jag-j commented on packages/code-analyzer-regex-engine/src/engine.ts
>          const ext: string = path.extname(fileName).toLowerCase();
@ravipanguluri - So, we don't check for binary files if the extension is specified? .exe or .bat files for example?

2024-08-07 21:29 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/engine.ts
>          const ext: string = path.extname(fileName).toLowerCase();
This follows from how Stephen checks it in the retire-js engine. Based on [documentation ](https://www.npmjs.com/package/isbinaryfile) for the underlying package, they don't seem to check by file extension, but by the contents of the file itself.  So i'm assuming in most .exe or .bat files, there's enough non-ASCII characters to raise alarm bells.

2024-08-08 15:23 UTC, stephen-carter-at-sf requested changes

2024-08-08 15:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +            (element, fieldPath) => ValueValidator.validateString(element, fieldPath, FILE_EXT_PATTERN), [])!;
OK we need to be careful here. If the user has [] in their config file... do we treat this as none or all? 
I would instead make rawFileExtensions be of type `string[] | undefined` here and do not supply a default value. This way, we know whether or not they supplied the value or not by checking if rawFileExtensions is undefined. If not then we can treat it as all. Otherwise, I believe we should accept `[]` as none from the user.

2024-08-08 15:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +            (element, fieldPath) => ValueValidator.validateString(element, fieldPath, FILE_EXT_PATTERN), [])!;
So please update line 30 and 31 so that
```
        /// The extensions of the files that you would like to test the regular expression against.
        file_extensions: string[];
```

it is instead something like:
```
        // The extensions of the files that you would like to test the regular expression against.
        // If not defined, or equal to null, the all text-based files of any file extension will be tested.
        file_extensions?: string[];
```

2024-08-08 15:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +        if (this.regexRules[ruleName].file_extensions.length === 0){
Along with my other comments, this should instead be:
```
if (this.regexRules[ruleName].file_extensions.length){
```

2024-08-08 15:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    const newlineIndexes = [-1];
Why did this change? Did you find a bug or something? Help me understand this a bit.

2024-08-08 15:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +import {isBinaryFileSync} from "isbinaryfile";
You are using isbinaryfile, but you didn't update package.json to add this dependency for this engine.
If the retire-js engine isn't installed... then this dependency would be missing.

Specifically us the same version as the retire-js engine as well:
    "isbinaryfile": "^5.0.2",

2024-08-08 15:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +            return isTextFile(fileName);
Please add in a //TODO here so that we eventually speed this up. If every single rule that doesn't have a file extension checks if the file is a text file (which is a slow operation) then we should be caching this information against the file. Let's fix the bug first, then refactor afterward.

2024-08-08 15:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    return !isBinaryFileSync(fileName);
Add in a //TODO so that we don't do this synchronously. We should optimize the performance here later on so that we aren't doing one file at a time synchronously. And do me a favor and add in //TODO inside of code-analyzer-retire-js-engine/src/utils.ts on line 63 with the same todo.

2024-08-08 15:46 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    const newlineIndexes = [-1];
Yes, I found a bug. Basically if a violation occurs at the very beginning of file without any newlines it reported the beginning position as line: 0, column: 0. It came up in one of the tests that I made. Should I leave it as-is for here and make the change in it's own PR.

2024-08-08 15:54 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    const newlineIndexes = [-1];
I'm all for fix as you go. Just was asking. Thanks.

2024-08-08 15:54 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    return !isBinaryFileSync(fileName);
In fact... while the TODO remains... let's try to short circuit this answer as much as possible. For now, create a constant in the file as a Set<string> that contains a set of all the most common text based file extensions. Then we can first just check the file extension - and if not... then we back up to use the isBinaryFileSync function for now.

2024-08-08 16:05 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/config.ts
> +            (element, fieldPath) => ValueValidator.validateString(element, fieldPath, FILE_EXT_PATTERN), [])!;
I see your point. I guess it just seemed odd to me that a user would want a rule that is run on no files. But thinking more, I can see some use cases.

2024-08-08 16:11 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    return !isBinaryFileSync(fileName);
How exhaustive should this set be? Should it just be the most common code files that we expect code analyzer to be run against?

2024-08-08 16:28 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    return !isBinaryFileSync(fileName);
Well the target audience is salesforce developers who will be dealing with salesforce files in a salesforce project. I'll send you a list of sample project repos in slack... just walk through some of those repos to get a good idea of what extensions might live in them.

2024-08-08 17:19 UTC, stephen-carter-at-sf requested changes

2024-08-08 17:19 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +        // If not defined, or equal to null, the all text-based files of any file extension will be tested.
"the all" should be "then all"

2024-08-08 17:19 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +const TEXT_BASED_FILE_EXTS = new Set<string>(
nitpick... no need to have each extension on its own line. It can probably fit on one or two lines.

Also, please alphabetize the list and add in a few more that I just thought of:
'.json', '.md', '.htm', '.page', '.csv', '.yml', '.yaml', '.mdt', '.xsl', '.xslt', '.rtf'

2024-08-08 17:19 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +        return isTextFile(fileName);
Since the ext is needed for the quick return, let's keep the isTextFile as it was before. and instead put the quick return logic here (so that later we only need to cache the things that we can't do quickly - keeping the cache small).

So basically I propose doing something like:
```
    const ext: string = path.extname(fileName).toLowerCase();
    return this.regexRules[ruleName].file_extensions ? 
        this.regexRules[ruleName].file_extensions.includes(ext) :
        TEXT_BASED_FILE_EXTS.includes(ext) || isTextFile(fileName);
```

2024-08-08 17:19 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    /*TODO: cache whether or not a file is text-based so calls to isTextFile() are minimized */
Now that I think about it... just move this comment down to isTextFile function

```
// TODO: Make this async and cache results to improve performance
function isTextFile(fileName: string): boolean {
    return !isBinaryFileSync(fileName);
}
```

2024-08-08 17:32 UTC, stephen-carter-at-sf approved these changes

2024-08-08 18:15 UTC, merged