NEW (RegexEngine) @W-16384199@ Create new default rules for regex engine
forcedotcom/code-analyzer-translator pull request #69
Opened 2024-08-09 20:51 UTC by ravipanguluri

In this PR:

* 4 new rules are introduced: UseInclusiveHierarchicalTerms, UseInclusiveSecurityTerms, UpdateOldApexApiVersion, UseInclusiveOutageTerms
* Rule attributes are exactly as defined in regex engine configuration document
* Rules are run and described with runRules()/describeRules() in any directory containing text-based files (since file extensions are not provided for these rules).

2024-08-12 18:28 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +    UseInclusiveSecurityTerms: {
John should be the one to decide whether these are rules we want to add, and what tags / severity levels they should be. You should set up a meeting with him.

2024-08-12 18:45 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +    UseInclusiveSecurityTerms: {
I have already set one up for tomorrow.

2024-08-13 17:56 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +    UseInclusiveSecurityTerms: {
As an update to this, I received approval on the rules from John with some minor updates which are reflected in the most recent changes.

2024-08-13 19:34 UTC, stephen-carter-at-sf requested changes

2024-08-13 19:34 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `One of the terms '%s or '%s' was found. Replace it with a more inclusive term like '%s' or '%s'"`,
1) It looks like your single quotes are a bit off in here. 
`'%s’` should be `'%s'`
`‘%s'` should be `'%s'`
`'%s` should be `'%s'`

2) What is with the two double quotes at the end of line 14? `""` And do we even want a quote at the beginning of line 14?
3) What is with the double quote at the end of line 17? `"`... should that instead be `.`?
4) What do you mean "for good and bad" ... Can we reword this or is this something you pulled from a doc page?
5) For AvoidColorizedTermsRuleDescription, instead of passing in exactly what we are looking for, can we make this more generic so that we can expand the list in the future if we wanted to. Something like a rule called AvoidTermsWithImplicitBias that has a simple description of:
`Detects usage of terms that reinforce implicit bias.`

6) The AvoidColorzedTermsRuleMessage... this looks a lot like the UseInclusiveHierarchicalTermsRuleMessage... can we instead reuse this message and not have it be `'%s' or '%s'` but just have what was found and what it should be replaced with? If we have multiple options, then maybe have the message be generic as something like:
`The term '%s' was found. Replace it with a more inclusive term, like one of the following: %s `
where %s here would be the output of JSON.stringify(stringArrayOfAcceptedTerms)

2024-08-13 19:34 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Detects Apex classes relying on API versions that are below 60.0`,
Can you look through all the the rule descriptions and determine whether or not the descriptions in general have a period `.` at the end or not and try to be consistent with all of our descriptions?

2024-08-13 19:34 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Found an Apex class relying on an API version 3 years or older. Update your API version.`,
This message seems different than the description. Also consider what happens 2 years from now... will this still say 3 years or older?

In fact, there is an open question on... should this rule keep getting updated dynamically instead of being fixed? If so, then shouldn't we calculate the rule version based on the current date or something? Or do we want the rule to be fixed in which case this message should just say "version 60.0".

What is the rule requirement here? If it indeed is to detect versions based on time and how old they are... then let's write a utility function that calculate based on dateTime what version was associated with that date. Then we can use that utility function to automatically update the rule everytime the version is expected to change. For example, I believe we have 3 releases a year (i.e. every 4 months). So if we know the estimated dates of when this will be... then we should be able to make this dynamic. I'd like to avoid having to keep updating this rule every 4 months manually.

2024-08-13 20:35 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Found an Apex class relying on an API version 3 years or older. Update your API version.`,
From the spike document, the intent of the rule is to detect when an API version is 3 years or older just to make sure that users are not relying on an API version that is very outdated. In that case, I can write a utility to do that.

2024-08-13 22:34 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `One of the terms '%s or '%s' was found. Replace it with a more inclusive term like '%s' or '%s'"`,
To clarify, for 5 the specific language is taken from the resource url for the [rule](https://www.salesforce.com/news/stories/salesforce-updates-technical-language-in-ongoing-effort-to-address-implicit-bias/). I agree the phrasing is a bit clunky though, so I'll make a second pass while keeping the intent the same.

2024-08-14 16:22 UTC, stephen-carter-at-sf requested changes

2024-08-14 16:22 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/test/utils.test.ts
> +    });
Can you make a test that will fail in the future but currently passes right now? That is use new Date() as input. It shouldn't throw  today but put a comment in that says if it throws the maxNumber must be between 0 and 99 in the future then the rule will need to be rewritten. Basically, we want our build to fail in the future with this error before it reaches customers.

2024-08-14 16:22 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/utils.ts
> +    }
* I see Winter '25 [v62.0] goes out in October (10/12/2024 specifically).
* I see the spring release typically goes out in February (like feb 12th I believe is when Spring 24 went GA on the R2b instances last year) - feb 15th 2024 will be Spring '25 [v63.0]. 
* I see  Summer '25 [v64.0] goes out in June (6/14/2025 specifically).

So shouldn't this be:
```
    if (month >= 1 && month < 5) { // Feb through May
        return (year - 2004) * 3;
    } else if (month >= 5 && month < 9) { // Jun through Sep
        return (year - 2004) * 3 + 1;
    } else { // Oct through Jan
        return (year - 2004) * 3 + 2;
    }
```

2024-08-14 16:35 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/utils.ts
> +    }
I had it as the first time that customers get the release since Salesforce tends to stagger their releases across multiple dates. But you're right that it makes much more sense to do it for the final release date.

2024-08-14 17:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +    UseInclusiveSecurityTerms: {
Please combine the 3 rules into one. I think your message catalog is revealing the true rule name: AvoidTermsWithImplicitBias.

2024-08-14 17:47 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +    UpdateOldApexApiVersion: {
Since all of our rules use negative wording... like "No*" and "Avoid*" maybe this should be something like "AvoidOldApiVersions"

2024-08-14 17:53 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Detects Apex classes relying on API versions that are below 52.0.`,
We either need to pass in the version here or or make it generic.

2024-08-14 17:53 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Found an Apex class relying on an API version 3 years or older. Update your API version.`,
Do we want the violation message to say what the minimum api version is and pass that in?

2024-08-14 17:56 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `"Detects usage of terms: %s which reinforce implicit bias.`,
I'd remove the semi colon here.
Also, I wonder if we need to actually display all the different terms we are looking for. If this grows to be really large, then do we want the rule description saying all of them.

I think having the list in the violation makes sense... but i'm on the fence about it being in the description. You can ask others what they think about this. Maybe it doesn't matter right now as long as the list is under 10 terms.

2024-08-15 15:56 UTC, stephen-carter-at-sf approved these changes

2024-08-15 15:56 UTC, merged