optional fields defined and tested
forcedotcom/code-analyzer-translator pull request #70
Opened 2024-08-09 23:35 UTC by ravipanguluri

In this PR:

A/C:

* Users can specify tags/severity levels for their custom rules at engines.regex.custom_rules configuration level.
* If a user doesn't give values for these fields, the same defaults as previously defined in configuration documentation will be maintained.

2024-08-12 18:27 UTC, stephen-carter-at-sf requested changes

2024-08-12 18:27 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +        const rawSeverityLevelValue: number | undefined = ruleExtractor.extractNumber('severity_level')
You are being too restrictive making this a number.
See 
https://github.com/forcedotcom/code-analyzer-core/blob/dev/packages/code-analyzer-core/src/config.ts#L163
and 
https://github.com/forcedotcom/code-analyzer-core/blob/dev/packages/code-analyzer-core/src/config.ts#L169

2024-08-12 18:44 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/config.ts
> +        const rawSeverityLevelValue: number | undefined = ruleExtractor.extractNumber('severity_level')
Ah I see. How should I integrate this extractor in for now then? Should I just copy-paste it for now with a TODO? Or would you want to move this to somewhere it can be used in core and the regex engine?

2024-08-12 19:02 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/config.ts
> +        const rawSeverityLevelValue: number | undefined = ruleExtractor.extractNumber('severity_level')
Disregard the previous comment. It needs to be modified slightly for the engine anyways, so I have my answer.

2024-08-12 22:36 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/config.ts
> +        const rawSeverityLevelValue: number | undefined = ruleExtractor.extractNumber('severity_level')
Slacked you something along these lines: but it's actually somewhat tricky to write a validator with the current engine API as it exists. The cleanest way I can think of changing validateType<T> to something like the following:

```
function validateType<T>(expectedTypes: string[], value: unknown, fieldPath: string): T {
    const dataType = getDataType(value);

    if (!expectedTypes.includes(dataType)) {
        throw new Error(getMessage('ConfigValueMustBeOfType', fieldPath, expectedTypes.join(' or '), dataType))
    }
    
    return value as T;
}
```

Then change the calls to validateType (in validateObject, validateBoolean, etc.) so the expected types are all wrapped in an array. In this case, I could make a simple validator like so: 

```
static validateNumberOrString(value: unknown, fieldPath: string): number | string {
        return validateType<number | string>(["number", "string"], value, fieldPath);
    }
```

If this is good, I can go ahead with it. Otherwise, if you have a different idea just let me know.

2024-08-13 13:24 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +        const rawSeverityLevelValue: number | undefined = ruleExtractor.extractNumber('severity_level')
what's wrong with the code in the links I sent. Can we not just copy/paste that validation code? (and in the future we can decide if we wanted to make it available via the engine-api or not)

```
function validateSeverityValue(value: unknown, valueKey: string): SeverityLevel {
    // Note that Object.values(SeverityLevel) returns [1,2,3,4,5,"Critical","High","Moderate","Low","Info"]
    if ((typeof value !== 'string' && typeof value !== 'number')
        || !Object.values(SeverityLevel).includes(value as string | number)) {
        throw new Error(getMessage('ConfigValueNotAValidSeverityLevel', valueKey,
            JSON.stringify(Object.values(SeverityLevel)), JSON.stringify(value)));
    }
    if (typeof value === 'string') {
        // We can't type cast to enum from a string, so instead we choose the enum based on the string as a key.
        value = SeverityLevel[value as keyof typeof SeverityLevel];
    }
    // We can type cast to enum safely from a number
    return value as SeverityLevel;
}
```

2024-08-13 14:58 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/config.ts
> +        const rawSeverityLevelValue: number | undefined = ruleExtractor.extractNumber('severity_level')
In this proposed solution I am using the validateSeverityValue function as-is. But i'm creating an extra layer to extract the number/string value in the config field before validating that it's a valid severity value. I can just use extractString()/extractNumber() to do this, but i'd have to verify the type of the value at that configuration field before calling the functions because they throw an error when you give them the wrong type.

2024-08-13 19:14 UTC, stephen-carter-at-sf requested changes

2024-08-13 19:14 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +    ConfigObject, ConfigValue,
nitpick, put each entry on its own line

2024-08-13 19:14 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +        // The severity levels correspond to numbers as follows: Critical = 1, High = 2, Moderate = 3, Low = 4, Info = 5
Instead of defining what tags are or what a severity level is... let's assume that they know. I slack messaged you with a link to a document that contains my updates to these comments.

2024-08-13 19:17 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +export const DEFAULT_TAGS: string[] = ['Recommended']
nitpick; end with semi-colon please. Lines 56, 57, 73 and any others that are needed.

2024-08-13 19:24 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/config.ts
> +    ConfigObject, ConfigValue,
I think auto-importing messes it up every time. I'll have to remind myself to check that before every PR.

2024-08-13 19:27 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/src/config.ts
> +        // The severity levels correspond to numbers as follows: Critical = 1, High = 2, Moderate = 3, Low = 4, Info = 5
I'm not seeing the slack message. Did you send it previously?

2024-08-14 13:15 UTC, stephen-carter-at-sf requested changes

2024-08-14 13:15 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +        severityLevel: SeverityLevel;
Oh wait... this should be severity instead of severityLevel so that we can be consistent with rule override section.

2024-08-14 13:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +        severityLevel: SeverityLevel;
I see that severityLevel is what the engineApi has on RuleDescription... and so it complicates things a bit. To resolve this for now, you'll need to set the value on both "severity" and "severityLevel" so as long as we have each of the RegexRules entries being an extended RuleDescription object for convenience. I have some ideas to clean this up afterward.

2024-08-14 13:24 UTC, stephen-carter-at-sf requested changes

2024-08-14 13:24 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/config.ts
> +        const rawSeverityLevelValue: ConfigValue = ruleExtractor.getObject()['severity_level'];
This should be 'severity' instead of 'severity_level' so that it matches the rule overrides section.

2024-08-14 14:04 UTC, stephen-carter-at-sf approved these changes

2024-08-14 16:00 UTC, merged