CHANGE (RegexEngine) @W-16462482@ Make isTextFile utility async and cache results of isBinaryFile() calls
forcedotcom/code-analyzer-translator pull request #71
Opened 2024-08-10 01:32 UTC by ravipanguluri

In this PR:

* isTextFile() will run asynchronously instead of synchronously
* When a file is checked to see if it is a text file (and will be scanned by rules that iterate through all text files) results are cached so that they can be retrieved so we can reduce calls to costly isBinaryFile() function

2024-08-10 01:37 UTC, ravipanguluri commented on packages/code-analyzer-regex-engine/test/end-to-end.test.ts
> -                    file_extensions: ['.ts', '.cls'],
I updated this test to verify that my cache works. I created a rule with no file extensions and pointed it to a workspace containing an ambiguous file (dummy1.py). When describeRules() was called, it should have cached that the file is a text file. Later, when runRules() checked if it should scan the file, it retrieved the cached result. I’m confident this worked because my code coverage is 100%, and no other test would trigger this retrieval.

2024-08-12 18:23 UTC, stephen-carter-at-sf requested changes

2024-08-12 18:23 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
>          }
Having an await in a loop doesn't help things all that much. Instead, we should be getting a promise array out and doing a Promise.all on it to then get a boolean array. This can then be used to quickly determine which ones to push.

2024-08-13 13:33 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +        return rules.filter((_rule: RuleDescription, index: number) => shouldDescribeResults[index]);
I see we are losing our quick returns (like the if(...some...)). Same issue we would face if we converted lines 44 through 46 to use Promise.all.

I have some ideas, can you schedule a meeting with me to discuss how we can boost performance here without losing the quick returns?

2024-08-13 19:04 UTC, stephen-carter-at-sf approved these changes
Just one small nitpick... but otherwise approved. Good work.

2024-08-13 19:04 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/engine.ts
> +    Violation, Workspace
nitpick, new line between entries

2024-08-13 19:18 UTC, merged