NEW (FlowTest) @W-16360741@ FlowTest engine validates local versions of Python.
forcedotcom/code-analyzer-translator pull request #73
Opened 2024-08-12 21:14 UTC by jfeingold35

2024-08-12 21:59 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/config.ts
Much of this file was derived from looking at the regex engine.

2024-08-12 21:59 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/engine.ts
> +        this.pythonVersionManager = new PythonVersionManager(dependencies.pythonVersionIdentifier, emitLogEventFunction);
Constructing the version manager within the class itself so I can pass the `emitLogEvent` function to the constructor instead of the `getPythonCommand` method.

2024-08-12 21:59 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/lib/python-versioning/PythonVersionIdentifier.ts
> +        return new Promise<SemVer>((res, rej) => {
The internals of this Promise may get refactored into a superclass for use when actually running the Python tool, but for now it's all in here.

2024-08-13 13:06 UTC, stephen-carter-at-sf requested changes

2024-08-13 13:06 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/plugin.ts
>      }
We should be validating the python version during createEngine. If python doesn't exist on the users machine, then we shouldn't be adding the engine to the list when selecting rules or running etc. So all validation should be done in createEngine if possible. This way, when the engine is constructed, it receives the normalized config with all validation done - so that it doesn't need to make validation its responsibility.
This also allows us to eventually move utilities like these into the engine api officially as an extractor method. I don't know if python will ever be used again, but for example, when we get to fetching the java version. It'll be nice to share that extraction routine among the SFGE and PMD engines.

All that to say, I recommend, you, as part of taking the raw config and converting it to a normalized config... have the normalized config have the derived values from the environment whenever the raw config doesn't supply it.

2024-08-13 13:09 UTC, stephen-carter-at-sf requested changes

2024-08-13 13:09 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/config.ts
> +    python_command_path?: string;
We should aim to have no optional values here. We should take the optional raw config and always (whenever possible) convert it to exact values. This way, we remove conditional code from the engine.

2024-08-14 22:57 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/config.ts
> +export interface FlowTestConfigFactory {
The config and its factory share the same file because it seemed excessive to have a file dedicated to one type.

2024-08-14 22:57 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/lib/python/PythonVersionIdentifier.ts
> +    identifyPythonVersion(pythonCommand: string): Promise<SemVer|null>;
CHANGE: This method now returns null when a version can't be parsed instead of throwing an error here. It makes the method signature a little more complicated but it keeps the upstream code much cleaner (and honestly simplifies some stuff here too).

2024-08-14 22:57 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/messages.ts
Messages have been changed aggressively.

2024-08-14 22:57 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/plugin.ts
> +    public _getConfigFactory(): FlowTestConfigFactory {
Calling attention to this part here. I couldn't think of a better way to force the plugin to use a stubbed factory than by having this method be publicly exposed and stubbed in tests.

2024-08-14 22:57 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/stubs/lib/python/StubPythonVersionIdentifier.ts
Stubs are now in their own top-level-rooted directory whose structure mirrors `src`. I like this convention, and may implement it on scanner v5.

2024-08-14 22:57 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/test/config.test.ts
Tests here are equivalent to the ones that used to be in `PythonVersionManager.test.ts`.

2024-08-15 19:01 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/plugin.ts
> +    public _getConfigFactory(): FlowTestConfigFactory {
I recommend passing in dependencies to constructor. For example
```
    private configNormalizer: FlowTestConfigNormalizer;

    public constructor(pythonVersionIdentifier: PythonVersionIdentifier = new RuntimePythonVersionIdentifier()) {
        this.configNormalizer = new ConfigNormalizer(pythonVersionIdentifier);
    }
...

    public async createEngine(engineName: string, rawConfig: ConfigObject): Promise<Engine> {
        ...
        const normalizedConfig: FlowTestConfig = await this.configNormalizer.normalize(rawConfig);
        return new FlowTestEngine(normalizedConfig);
    }
```

Note that in my version I renamed your `PythonVersionIdentifierImpl` to be `RuntimePythonVersionIdentifier`. Also I renamed your `FlowTestConfigFactory` to be `ConfigNormalizer` (I don't think you need an interface here) since I think all engines will basically have this normalization step at some point so I like the name.

These are just suggestions, but I hope that helps.

2024-08-15 19:08 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/stubs/stub-config.ts
> +export class StubFlowTestConfigFactory implements FlowTestConfigFactory {
What is this for? We can just stub out the Version Identifier can't we?

Oh wait... I see now... your PythonVersionIdentifer should probably instead be a class that gives both... the version and the path. Then you just need to stub 1 class.

2024-08-15 21:18 UTC, stephen-carter-at-sf requested changes

2024-08-15 21:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/config.ts
> +}
Not sure why this dependencies type is needed. Why not just store the pythonVersionIdentifier on the ConfigNormalizer directly?

2024-08-15 21:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/test/config.test.ts
> +describe('FlowTestConfigFactory implementations', () => {
Can we instead test through the front door (i.e. the plugin's createEngine method) so that we don't couple our tests to implementation details. This is the reason why the plugin receives in its constructor its dependencies.

2024-08-15 21:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/test/lib/python/PythonVersionIdentifier.test.ts
> +            //       So we'll tell it to provide Node's version, and then just compare that to the version of this node process.
Why can't we? We can add it to our test environment's github workflow.

2024-08-15 21:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/test/plugin.test.ts
>      it('#createEngine() throws error when asked for an unsupported engine', async () => {
I was expecting all of the configuration testing to be done here as well instead of in the config.test.ts file since the public entry point for core (the client of this engine) is the createEngine method.

2024-08-15 21:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/tsconfig.json
> +    "./stubs"
Why not put stubs as a subdirectory underneath the test directory? Or better yet inside of the test directory simply as a file called stubs.ts

2024-08-15 21:21 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/config.ts
> +}
It seemed like better future-proofing in case we need to start passing in more things. But yeah I could just pass the identifier in directly.

2024-08-15 21:24 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/test/lib/python/PythonVersionIdentifier.test.ts
> +            //       So we'll tell it to provide Node's version, and then just compare that to the version of this node process.
I meant we shouldn't necessarily assume that a _dev's_ machine has Python on it...

2024-08-15 21:25 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/test/config.test.ts
> +describe('FlowTestConfigFactory implementations', () => {
I'm not sure I understand. In what way is this more coupled to the implementation than the alternative?

2024-08-15 21:27 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/tsconfig.json
> +    "./stubs"
Having them all in one file might work here, but it's definitely not workable for the other projects. And having `stubs` at the top level seemed cleaner to me, though I'm happy to move it back down too.

2024-08-15 21:30 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/config.ts
> +}
Done.

2024-08-15 21:55 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/test/config.test.ts
> +describe('FlowTestConfigFactory implementations', () => {
If you look at eslint, regex, engines for example... you'll see that the tests don't instantiate any helper tools or classes... instead it always uses the plugin interface. This way as we keep updating the implementation and refactoring - we never need to update the tests.

Adding in a _getFlowTestConfig method on the engine is helpful here.

So each test is a plugin test. You construct the plugin for test purposes (passing in any test specific stubs or dependencies)... and then call createEngine('flowtest',rawConfig) and validate what you expect... which might be simply validating that the engine that you have received has the correct config handed to it (in which you can use test only engine._getFlowTestConfig() method).

2024-08-15 21:57 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/test/lib/python/PythonVersionIdentifier.test.ts
> +            //       So we'll tell it to provide Node's version, and then just compare that to the version of this node process.
I suppose... it's just a funny test in my opinion using node instead of python. I think it is reasonable to assume that developers will have python 3+ on their machine. But if you are truly worried then maybe we make this code conditional on an environment variable that we set inside of github. Just thinking out loud. I would love to hear Jag's thoughts on this one to be honest - because i'm on the fence.

2024-08-15 21:58 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/tsconfig.json
> +    "./stubs"
I think we should be cautious with premature optimization in this case. I don't think the flowtest is going to have a lot of stubs. In fact, i would argue that a stub should be in the file it is used in unless it is shared across files. So I personally would just put the stub at the bottom of your plugin.test.ts file

2024-08-21 14:16 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/tsconfig.json
> +    "./stubs"
Yeah, I'm pretty sure most of the stubs are only going to be used in one test file, so I'll move the one I have into that test file for now.

2024-08-21 14:16 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/test/lib/python/PythonVersionIdentifier.test.ts
> +            //       So we'll tell it to provide Node's version, and then just compare that to the version of this node process.
@jag-j , do you have thoughts on this?

2024-08-21 14:54 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/tsconfig.json
> +    "./stubs"
Actually never mind. The stubs are used in multiple files. So I'll just move them into a `test/stubs/` folder and have that folder be flat.

2024-08-23 19:55 UTC, stephen-carter-at-sf approved these changes

2024-08-23 22:08 UTC, merged