NEW @W-16360876@ Implemented describeRules() functionality for FlowTest
forcedotcom/code-analyzer-translator pull request #93
Opened 2024-09-25 19:32 UTC by jfeingold35

2024-09-25 19:43 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/.gitignore
> +FlowTest/build/**/**
I added a .gitignore to FlowTest to prevent files that don't belong from getting committed again.

2024-09-25 19:43 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/engine.ts
> +    public constructor(commandWrapper: FlowTestCommandWrapper) {
Passing the wrapper into the constructor allows us to replace it with a stub during tests.

2024-09-25 19:43 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/engine.ts
> +                name: flowTestRule.query_name,
The `query_name` field has spaces in it, and the `query_id` field has periods in it. So I chose to use the one with spaces in it for now. We can have a discussion about what postprocessing might be needed to bring the names more into line with our best practices.

2024-09-25 19:43 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/python/FlowTestCommandWrapper.ts
> +        return (JSON.parse(stdout) as FlowTestRuleDescriptor[]).sort((a, b) => a.query_name.localeCompare(b.query_name));
The sorting is necessary because the output printed to stdout isn't sorted at this time. Robert intends to update it with sorting, and when he does I will change it here too.

2024-09-26 17:07 UTC, jag-j commented on packages/code-analyzer-flowtest-engine/src/python/FlowTestCommandWrapper.ts
> +export type FlowTestRuleDescriptor = {
Nit: The rule for each of the engines is defined in different places. It will be good if they all follow the same convention. I personally like how regex engine has this in config.ts.

2024-09-26 17:17 UTC, jag-j commented on packages/code-analyzer-flowtest-engine/src/python/FlowTestCommandWrapper.ts
> +export type FlowTestRuleDescriptor = {
I think it will also help to add some description on the fields.

2024-09-26 17:51 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/python/FlowTestCommandWrapper.ts
> +export type FlowTestRuleDescriptor = {
Reasonable. I'll get on that.

2024-09-26 18:51 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/python/FlowTestCommandWrapper.ts
> +export type FlowTestRuleDescriptor = {
Actually, while I agree that the fields definitely need descriptions, I think it makes more sense for the definition to stay in the Wrapper file, since it's more closely related to interaction with the Python layer than anything else. That's how the PMD integration does it as well, so there's precedent.

2024-09-26 19:39 UTC, jag-j commented on packages/code-analyzer-flowtest-engine/src/python/FlowTestCommandWrapper.ts
> +export type FlowTestRuleDescriptor = {
Sounds good. For something like regexengine that doesn't need a wrapper, it is in config.

2024-09-26 19:39 UTC, jag-j approved these changes

2024-09-30 18:18 UTC, stephen-carter-at-sf requested changes

2024-09-30 18:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/test/test-data/goldfiles/FlowTestCommandWrapper.test.ts/catalog.json
If you name this file catalog.goldfile.json then it'll automatically get the benefit of having linebreaks treated as linux always via: https://github.com/forcedotcom/code-analyzer-core/blob/dev/.gitattributes

2024-09-30 18:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/test/engine.test.ts
I see that code coverage for this flowtest package is no longer 100% like all other packages
```
 code-analyzer-flowtest-engine/src        |     100 |      100 |     100 |     100 |                   
  config.ts                               |     100 |      100 |     100 |     100 |                   
  engine.ts                               |     100 |      100 |     100 |     100 |                   
  messages.ts                             |     100 |      100 |     100 |     100 |                   
  plugin.ts                               |     100 |      100 |     100 |     100 |                   
 code-analyzer-flowtest-engine/src/python |   90.56 |    44.44 |   77.77 |   92.15 |                   
  FlowTestCommandWrapper.ts               |     100 |      100 |     100 |     100 |                   
  PythonCommandExecutor.ts                |   78.26 |    28.57 |      70 |   80.95 | 35-45             
  PythonVersionIdentifier.ts              |     100 |      100 |      80 |     100 |                     
```
If possible, can we either add in code coverage for anything to be submitted or add in the ignore comments where code coverage isn't easily able to be covered?
  
 Or will these be hit when the run method is implemented?

2024-09-30 18:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/engine.ts
>      public async describeRules(_describeOptions: DescribeOptions): Promise<RuleDescription[]> {
The describe command should be looking at the workspace if it is provided to see if the workspace even contains relevant files (in this case, flow based xml files). If there is a workspace and there are no relevant files, then no rules should be returned. That is, we shouldn't be doing any work if there are no flow files in the workspace.

2024-09-30 18:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/engine.ts
> +    private convertFlowTestRulesToCodeAnalyzerRules(flowTestRules: FlowTestRuleDescriptor[]): RuleDescription[] {
Nitpick: Can these private methods instead be functions? 

Also maybe call this function `toRuleDescription(flowTestRule: FlowTestRuleDiscriptor)` and then simply make your line 29 to be 
```
const ruleDescriptions: RuleDescription[] = flowTestRules.map(toRuleDescription);
```

2024-09-30 18:18 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/python/FlowTestCommandWrapper.ts
> +        return JSON.parse(stdout) as FlowTestRuleDescriptor[];
We shouldn't be processing stdout if at all possible because other things can end up in the stdout that we don't want... or stdout can clip if the output is long and the environment caps the buffer. Does flowtest allow us to write the output to a file? If so, we should be reading that file and parsing its output - all in a try catch so that if reading or parsing fails, we know what step it failed at.

2024-09-30 18:18 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/test/test-data/goldfiles/FlowTestCommandWrapper.test.ts/catalog.json
Good catch.

2024-09-30 20:50 UTC, jfeingold35 commented on packages/code-analyzer-flowtest-engine/src/engine.ts
>      public async describeRules(_describeOptions: DescribeOptions): Promise<RuleDescription[]> {
It looks like the extensions the FlowTest tool looks for are `.flow-meta.xml` and `.flow`. So I'll make the plugin look for those too.

2024-10-01 13:05 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/test/engine.test.ts
Improved: Now I see
```
------------------------------------------|---------|----------|---------|---------|-------------------
File                                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------------------------------|---------|----------|---------|---------|-------------------
PythonVersionIdentifier.ts              |     100 |      100 |      80 |     100 |           
```
Maybe there is 1 function that isn't fully hit.

2024-10-01 13:28 UTC, stephen-carter-at-sf requested changes

2024-10-01 13:28 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/engine.ts
> +        const convertedRules = flowTestRules.map(r => toRuleDescription(r));
Since it is now a function (and not tied to a class instance), I believe you could have also just done `flowTestRules.map(toRuleDescription)`

2024-10-01 13:28 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/engine.ts
> +        name: flowTestRule.query_name,
It looks like in the catalog.goldfile.json that an example query_name is `Flow: SystemModeWithSharing recordUpdates data` and here it looks like we are using this as the rule name. This does not seem good to me.

Robert closed the Enhancement Request for rules having shorter names (see https://git.soma.salesforce.com/SecurityTools/FlowSecurityLinter/issues/39) ... but it looks like he maintained spaces and colons in the names. For example I see

```query_name = f"Flow Security: User access to {elem_type} {check_labels_val} in mode {run_mode}"```
got turned into
```
query_name = f"Flow: {run_mode} {elem_type} {check_labels_val}"
```
which is still too long.

So either we need to go back to him and make these names even shorter without spaces and colons, or we'll need to create a mapping on our end (either fixed or dynamic).

For example on our end we could probably just remove the prefix "Flow: " and then convert all spaces to dashes for now or something. So instead of
`Flow: SystemModeWithSharing recordUpdates data` maybe the name could for now just be `SystemModeWithSharing-recordUpdates-data`

But I created https://git.soma.salesforce.com/SecurityTools/FlowSecurityLinter/issues/47 to ask that we may receive better names.

2024-10-02 15:04 UTC, stephen-carter-at-sf commented on packages/code-analyzer-flowtest-engine/src/engine.ts
> +                this.emitLogEvent(LogLevel.Fine, 'Workspace contains no Flow files; returning no rules');
This seems relevant to possible user debugging... so maybe make this to LogLevel.Debug instead of LogLevel.Fine.

2024-10-02 16:28 UTC, stephen-carter-at-sf approved these changes

2024-10-02 16:29 UTC, merged