NEW (RegexEngine) @W-15490095@ Rule to reduce calls to Limits.getHeapSize()
forcedotcom/code-analyzer-translator pull request #96
Opened 2024-10-01 17:16 UTC by jag-j

2024-10-01 17:24 UTC, jag-j commented on packages/code-analyzer-regex-engine/src/messages.ts
> +    AvoidGetHeapSizeInLoopRuleDescription:
@jshackell-sfdc: Can you please review these two messages? Thank you!

2024-10-01 18:36 UTC, jshackell-sfdc approved these changes
See my edits!

2024-10-01 18:36 UTC, jshackell-sfdc commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Detects usage of Limits.getHeapSize() in loops`,
```suggestion
        `Detects usage of Limits.getHeapSize() in loops. We recommend you avoid this pattern due to performance and resource reasons.`,
```

2024-10-01 18:36 UTC, jshackell-sfdc commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Found the use of Limits.getHeapSize() in a loop`,
```suggestion
        `Found the use of Limits.getHeapSize() in a loop. We recommend you avoid this pattern due to performance and resource reasons.`,
```

2024-10-01 18:39 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Detects usage of Limits.getHeapSize() in loops`,
The rule description should be somewhat short... but the violation message can be longer. So I think the "We recommend" stuff shouldn't be here in the description but should indeed be in the `AvoidGetHeapSizeInLoopRuleMessage`

2024-10-01 18:48 UTC, jshackell-sfdc commented on packages/code-analyzer-regex-engine/src/messages.ts
> +        `Detects usage of Limits.getHeapSize() in loops`,
Okay!  Whatever you think best.

2024-10-01 19:02 UTC, stephen-carter-at-sf requested changes

2024-10-01 19:02 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            tags: ['Recommended', 'Performance']
This is fine... but eventually we'll need to reevaluate all the tags for all of our rules accross all engines to determine (besides Recommended) what the standard tag categories should be.

2024-10-01 19:02 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(for|while)\s*\([^)]*\)\s*\{[^}]*\bLimits\.getHeapSize\(\);|do\s*\{[^}]*\}\s*while\s*\([^)]*\);/gi).toString(),
Concerns:
* First, we aren't checking for whether the code lives in comments. Probably can't do that anyway - just want to make sure this limitation is known
* Second, for the first for|while case... if the user puts an if statement inside of their loop prior to Limits.getHeapSize then this regular expression will assume we already exited the loop when it finds the first closed curly bracket. Regular expressions have been proven to not know the level of depth a specific bracket is for... so there are many edge cases where we might not alert when we should.
* Third, there might be scenarios where we actually have a Limits.getHeapSize inside of a loop that aren't really being invoked by the loop... maybe an anonymous function or class is being defined in the loop and has part of its definition the Limits.getHeapSize() call... not sure what user can or can't do with apex - just calling out that some edge cases there might exist.
* Fourth, the do loop doesn't seem to even be checking for the getHeapSize function at all... so wouldn't this just pick up like every do loop?

In general, I think we might only be able to get this working 95% of the time at best. It really should be added to PMD engine instead in my opinion.

2024-10-01 20:46 UTC, jag-j commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(for|while)\s*\([^)]*\)\s*\{[^}]*\bLimits\.getHeapSize\(\);|do\s*\{[^}]*\}\s*while\s*\([^)]*\);/gi).toString(),
As discussed offline, checking if the code is commented is a known limitation. I have taken care of the Fourth issue. Regarding second and third, I agree with the limitations. But PMD also has limitations if the Limit.getHeapSize() is within a function that is called from a loop. Graph Engine would be the most accurate, but it's also the most expensive, both in terms of implementation and time for users to get results. The Regex engine is the least expensive, which is why I slightly preferred it over PMD. It also gave us an opportunity to utilize the new engine we built from the ground up.

2024-10-02 16:58 UTC, stephen-carter-at-sf approved these changes

2024-10-02 17:01 UTC, stephen-carter-at-sf commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(for|while)\s*\([^)]*\)\s*\{[^}]*\bLimits\.getHeapSize\(\);|do\s*\{[^}]*\}\s*while\s*\([^)]*\);/gi).toString(),
I approved the PR but I do believe having a if statement before Limits.getHeapSize() is still something PMD would handle and not care about.... but what kills this particular regex based rule.

2024-10-02 18:24 UTC, jag-j commented on packages/code-analyzer-regex-engine/src/plugin.ts
> +            regex: (/(for|while)\s*\([^)]*\)\s*\{[^}]*\bLimits\.getHeapSize\(\);|do\s*\{[^}]*\}\s*while\s*\([^)]*\);/gi).toString(),
Agreed! I'll bring it up with the Apex team and get in their inputs as well.

2024-10-03 22:25 UTC, merged